<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260328185412 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE submitted_invoices (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, session_ref VARCHAR(255) NOT NULL, invoice_ref VARCHAR(255) NOT NULL, submitted_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_submitted_invoices_submitted_at ON submitted_invoices (submitted_at)');
        $this->addSql('CREATE UNIQUE INDEX uq_session_invoice_ref ON submitted_invoices (session_ref, invoice_ref)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE submitted_invoices');
    }
}
