controllers:
    resource: ../src/Frontend/Dashboard/UI/Action/
    type: attribute

contractors:
    resource: ../src/Frontend/Contractors/UI/Action/
    type: attribute

settings:
    resource: ../src/Frontend/Settings/UI/Action/
    type: attribute

invoice_generation:
    resource: ../src/Backend/InvoiceGeneration/UI/Action/
    type: attribute

reports:
    resource: ../src/Frontend/Reports/UI/Action/
    type: attribute
