parameters:
    ksef.nip: '%env(KSEF_NIP)%'
    ksef.certificate_path: '%env(KSEF_CERTIFICATE_PATH)%'
    ksef.certificate_password: '%env(KSEF_CERTIFICATE_PASSWORD)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Ksef\:
        resource: '../src/'

    Ksef\Api\KsefApiService:
        arguments:
            $httpClient: '@http_client'
            $ksefNip: '%ksef.nip%'
            $certificatePath: '%ksef.certificate_path%'
            $certificatePassword: '%ksef.certificate_password%'
